name: "Release from tag"
# Defines when this build file will run.
on:
  push:
    tags:
      - '*'

jobs:
  release-from-tag:
    runs-on: ubuntu-latest
    steps:
      - name: (local) Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/checkout@v2
        with:
          path: changelog-action

      - name: (local) Update CHANGELOG
        id: changelog
        uses: ./
        with:
          jiraBrowseUrl: https://jira.finods.com/browse
          jiraPrefixes: 'SL, SBKRESP, LPS'
          token: ${{ github.token }}
          tag: ${{ github.ref_name }}

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          draft: false
          name: ${{ github.ref_name }}
          body: ${{ steps.changelog.outputs.changes }}
          token: ${{ github.token }}

      - name: Commit CHANGELOG.md
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: main
          commit_message: 'docs: update CHANGELOG.md for ${{ github.ref_name }} [skip ci]'
          file_pattern: CHANGELOG.md
