name: "Release from tag"
# Defines when this build file will run.
on:
  push:
    tags:
      - '*'

jobs:
  release-from-tag:
    runs-on: ubuntu-latest
    steps:
      - name: (local) Checkout Code
        uses: actions/checkout@v2
        if: ${{ always() }}
        with:
          fetch-depth: 0
          path: changelog-action

      - name: (local) Update CHANGELOG
        if: ${{ always() }}
        uses: ./
        with:
          token: ${{ github.token }}
          tag: ${{ github.ref_name }}
